version: '3.8'
services:
  db:
    image: postgis/postgis:13-3.3
    environment:
      POSTGRES_DB: engine
      POSTGRES_USER: engine
      POSTGRES_PASSWORD: changeme
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:6-alpine
    networks:
      - backend

  worker:
    build: ./worker
    command: celery -A tasks worker --loglevel=INFO
    depends_on:
      - redis
      - db
    networks:
      - backend

  api:
    build: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - worker
      - db
      - redis
    networks:
      - backend

  updater:
    build: ./updater
    command: python etl/update_pipeline.py
    depends_on:
      - db
    networks:
      - backend

  tiles:
    image: klokantech/tileserver-gl
    volumes:
      - ./web_map/tiles.mbtiles:/data/tiles.mbtiles
    ports:
      - "8080:80"
    networks:
      - backend

  ui:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - api
      - tiles
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
